#!/usr/bin/env python3
"""Generate seed_users.sql for Atrium WebSocket benchmark.

Creates N test users with PBKDF2-SHA256 hashed passwords and adds them
to a target room's room_members table.
"""

import argparse
import hashlib
import os
import time


def hash_password(password: str) -> tuple[bytes, bytes]:
    salt = os.urandom(16)
    h = hashlib.pbkdf2_hmac("sha256", password.encode(), salt, 100000, dklen=32)
    return salt, h


def main():
    parser = argparse.ArgumentParser(description="Generate benchmark seed SQL")
    parser.add_argument("--start-id", type=int, default=1000, help="Starting user ID")
    parser.add_argument("--room-id", type=int, required=True, help="Target room ID")
    parser.add_argument("--password", default="bench123", help="Password for all users")
    parser.add_argument("--count", type=int, default=100, help="Number of users")
    args = parser.parse_args()

    now_ms = int(time.time() * 1000)
    participants_sql = []
    users_sql = []
    members_sql = []

    for i in range(args.count):
        user_id = args.start_id + i
        username = f"user_{i}"
        salt, h = hash_password(args.password)

        participants_sql.append(
            f"INSERT INTO participants (id, kind, display_name, avatar_url, created_at_ms) "
            f"VALUES ({user_id}, 1, '{username}', NULL, {now_ms});"
        )
        users_sql.append(
            f"INSERT INTO users (id, username, salt, password_hash) "
            f"VALUES ({user_id}, '{username}', 0x{salt.hex()}, 0x{h.hex()});"
        )
        members_sql.append(
            f"INSERT INTO room_members (room_id, user_id, role, join_at_ms) "
            f"VALUES ({args.room_id}, {user_id}, 2, {now_ms});"
        )

    print("-- Auto-generated by gen_seed.py")
    print(f"-- {args.count} users: user_0 .. user_{args.count - 1}")
    print(f"-- room_id = {args.room_id}, password = '{args.password}'")
    print()
    print("-- Participants")
    print("\n".join(participants_sql))
    print()
    print("-- Users")
    print("\n".join(users_sql))
    print()
    print("-- Room memberships")
    print("\n".join(members_sql))


if __name__ == "__main__":
    main()
